[font]
size = 13.0

[font.normal]
family = "Maple Mono NF"
style = "Medium"

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.italic]
family = "Maple Mono NF"
style = "Italic"

[window]
decorations = "None"
opacity = 1
# ملاحظة: Alacritty لا يدعم Blur داخلي، استخدم Niri للـ Blur
padding = { x = 2, y = 2 } # بديل window-padding-balance

[mouse]
hide_when_typing = true

# استيراد الثيم (تأكد أنك حملت catppuccin-mocha.toml في نفس المجلد)
[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
