$primary_paletteKeyColor = 7171ac
$secondary_paletteKeyColor = 76758e
$tertiary_paletteKeyColor = 9e648e
$neutral_paletteKeyColor = 78767b
$neutral_variant_paletteKeyColor = 777680
$background = 181825
$onBackground = e5e1e7
$surface = 181825
$surfaceDim = 1a1829
$surfaceBright = 3a3950
$surfaceContainerLowest = 16161f
$surfaceContainerLow = 1f1e2b
$surfaceContainer = 242338
$surfaceContainerHigh = 2d2c43
$surfaceContainerHighest = 36354c
$onSurface = e5e1e7
$surfaceVariant = 4a4957
$onSurfaceVariant = c8c5d1
$inverseSurface = e5e1e7
$inverseOnSurface = 1a1825
$outline = 918f9a
$outlineVariant = 918f9a
$shadow = 000000
$scrim = 000000
$surfaceTint = f5e0dc
$primary = f5e0dc
$onPrimary = 2a2a60
$primaryContainer = f5e0dc
$onPrimaryContainer = 181825
$inversePrimary = 595992
$secondary = c6c4e0
$onSecondary = 2e2e44
$secondaryContainer = 585b70
$onSecondaryContainer = bac2de
$tertiary = fab387
$onTertiary = 181825
$tertiaryContainer = bb7da9
$onTertiaryContainer = 000000
$error = f38ba8
$onError = 181825
$errorContainer = f38ba8
$onErrorContainer = 181825
$primaryFixed = e2dfff
$primaryFixedDim = f5e0dc
$onPrimaryFixed = 14134a
$onPrimaryFixedVariant = 414178
$secondaryFixed = e2e0fd
$secondaryFixedDim = c6c4e0
$onSecondaryFixed = 19192e
$onSecondaryFixedVariant = 45455c
$tertiaryFixed = ffd7f0
$tertiaryFixedDim = f5b2e0
$onTertiaryFixed = 35082e
$onTertiaryFixedVariant = 68355c
$term0 = 1e1e2f
$term1 = ac73ff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 99aad8
$term5 = b49fea
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = c093ff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b5c1dd
$term13 = c9b5f4
$term14 = bae0ff
$term15 = ffffff
$rosewater = f5e0dc
$flamingo = f2cdcd
$pink = f5c2e7
$mauve = cba6f7
$red = f38ba8
$maroon = eba0ac
$peach = fab387
$yellow = f9e2af
$green = a6e3a1
$teal = 94e2d5
$sky = 89dceb
$sapphire = 74c7ec
$blue = 89b4fa
$lavender = b4befe
$klink = 7382d2
$klinkSelection = 7382d2
$kvisited = 8172da
$kvisitedSelection = 8172da
$knegative = a167ff
$knegativeSelection = a167ff
$kneutral = ca92ff
$kneutralSelection = c992ff
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = cdd6f4
$subtext1 = bac2de
$subtext0 = a6adc8
$overlay2 = 9399b2
$overlay1 = 7f849c
$overlay0 = 6c7086
$surface2 = 585b70
$surface1 = 45475a
$surface0 = 313244
$base = 1e1e2e
$mantle = 181825
$crust = 1a1829
$success = a6e3a1
$onSuccess = 181825
$successContainer = 181825
$onSuccessContainer = a6e3a1
