#!/usr/bin/env bash
# Requires jq

ACTION=$1 # focus or move
DIRECTION=$2 # up or down

# Active window info
active_monitor=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true)')
current_ws=$(echo "$active_monitor" | jq -r '.activeWorkspace.id')
active=$(hyprctl activewindow -j)
aw_address=$(echo "$active" | jq -r '.address')
if [ -n "$aw_address" ]; then
  aw_y=$(echo "$active" | jq '.at[1]')
  aw_h=$(echo "$active" | jq '.size[1]')
else
  aw_y=0
  aw_h=0
fi

if [ "$DIRECTION" = "down" ]; then
    boundary=$((aw_y + aw_h))
    cmp='(.at[1] > $boundary)'
else
    boundary=$aw_y
    cmp='(.at[1] + .size[1] < $boundary)'
fi

# Get all windows on current workspace
windows=$(hyprctl clients -j | jq --argjson ws "$current_ws" '.[] | select(.workspace.id == $ws)')

# Find the first window in the given direction
next_win=$(echo "$windows" | jq -r --argjson boundary "$boundary" '
    select('"$cmp"') | .address
' | head -n1)

if [ -n "$next_win" ]; then
    # Focus that window
    
    if [ "$ACTION" = "focus"]; then
      hyprctl dispatch focuswindow address:$next_win
    elif [ "$ACTION" = "move" ]; then
      direction_key=$([ "$DIRECTION" = "down" ] && echo "d" || echo "u")
        hyprctl dispatch layoutmsg movewindowto "$direction_key"
    fi
else
    if [ "$current_ws" -eq 9 ] && [ "$DIRECTION" = "down" ]; then
      target_ws=1
    elif [ "$current_ws" -eq 1 ] && [ "$DIRECTION" = "up" ]; then
      target_ws=9
    elif [ "$DIRECTION" = "down" ]; then
      target_ws=$((current_ws + 1))
    elif [ "$DIRECTION" = "up" ]; then
      target_ws=$((current_ws - 1))
    fi

    if [ "$ACTION" = "focus" ]; then
      hyprctl dispatch workspace "$target_ws"
    elif [ "$ACTION" = "move" ]; then
      hyprctl dispatch movetoworkspace "$target_ws"
    fi
fi
